### ISSUE TITLE
Bug: Extension fails to start - it tries to install non-existant version of @angular/language-server

### ISSUE THREAD

**Issue by nevadascout** [nathansbradshaw/zed-angular#6]
I've installed the extension as instructed (by cloning the repo, then installing a dev extension). It appears to have installed successfully (it is visible on the installed extensions list), but it fails to start the language server.

I also have the HTML, SCSS and XML extensions installed.

Some extra info:
* MacOS 15.0.1 (Sequoia) on M2 Pro
* Node `v20.16.0`
* Zed `0.157.5`
* Angular `18.1.2`
* Typescript `5.4.5`

My Angular app is in a monorepo and there are two package.json files with different contents - one at the top level, and another within a subfolder (`now-src/`) where my Angular project lives. I have Zed opened to the root of the monorepo.

**The error appears to be that it is trying to install `@angular/language-server@5.6.3` which does not exist.** It is also a very old version (the latest is `v18.2.0`).

Here is the relevant excerpt from the logs showing the errors related to zed-angular
```
2024-10-22T10:08:01.594563+02:00 [INFO] attempting to start language server "ts", path: "/Users/nevadascout/dev/snip/now/ui", id: 3
2024-10-22T10:08:01.594721+02:00 [INFO] attempting to start language server "vscode-angular-language-server", path: "/Users/nevadascout/dev/snip/now/ui", id: 4
2024-10-22T10:08:01.595428+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:08:04.085774+02:00 [ERROR] Failed to start language server "ts": failed to execute npm install subcommand:
stdout: ""
stderr: "npm error code ETARGET\nnpm error notarget No matching version found for @angular/language-server@5.6.3.\nnpm error notarget In most cases you or one of your dependencies are requesting\nnpm error notarget a package version that doesn't exist.\nnpm error A complete log of this run can be found in: /Users/nevadascout/Library/Application Support/Zed/node/cache/_logs/2024-10-22T08_08_03_929Z-debug-0.log\n"
2024-10-22T10:08:04.08592+02:00 [ERROR] server stderr: ""
2024-10-22T10:08:05.327147+02:00 [ERROR] Failed to start language server "vscode-angular-language-server": failed to execute npm install subcommand:
stdout: ""
stderr: "npm error code ETARGET\nnpm error notarget No matching version found for @angular/language-server@5.6.3.\nnpm error notarget In most cases you or one of your dependencies are requesting\nnpm error notarget a package version that doesn't exist.\nnpm error A complete log of this run can be found in: /Users/nevadascout/Library/Application Support/Zed/node/cache/_logs/2024-10-22T08_08_05_192Z-debug-0.log\n"
2024-10-22T10:08:05.327283+02:00 [ERROR] server stderr: ""
```

Here is the full npm logfile that it references in the Zed log:
```
❯ cat 2024-10-22T08_08_05_192Z-debug-0.log
0 verbose cli /Users/nevadascout/.nvm/versions/node/v20.16.0/bin/node /Users/nevadascout/.nvm/versions/node/v20.16.0/bin/npm
1 info using npm@10.8.1
2 info using node@v20.16.0
3 silly config load:file:/Users/nevadascout/.nvm/versions/node/v20.16.0/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/nevadascout/Library/Application Support/Zed/extensions/work/angular/.npmrc
5 silly config load:file:/Users/nevadascout/Library/Application Support/Zed/node/blank_user_npmrc
6 silly config load:file:/Users/nevadascout/Library/Application Support/Zed/node/blank_global_npmrc
7 verbose title npm install @angular/language-server@5.6.3
8 verbose argv "install" "--cache" "/Users/nevadascout/Library/Application Support/Zed/node/cache" "--userconfig" "/Users/nevadascout/Library/Application Support/Zed/node/blank_user_npmrc" "--globalconfig" "/Users/nevadascout/Library/Application Support/Zed/node/blank_global_npmrc" "@angular/language-server@5.6.3" "--save-exact" "--fetch-retry-mintimeout" "2000" "--fetch-retry-maxtimeout" "5000" "--fetch-timeout" "5000" "--prefix" "/Users/nevadascout/Library/Application Support/Zed/extensions/work/angular"
9 verbose logfile logs-max:10 dir:/Users/nevadascout/Library/Application Support/Zed/node/cache/_logs/2024-10-22T08_08_05_192Z-
10 verbose logfile /Users/nevadascout/Library/Application Support/Zed/node/cache/_logs/2024-10-22T08_08_05_192Z-debug-0.log
11 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
12 silly logfile start cleaning logs, removing 2 files
13 silly logfile done cleaning log files
14 silly idealTree buildDeps
15 silly fetch manifest @angular/language-server@5.6.3
16 silly packumentCache full:https://registry.npmjs.org/@angular%2flanguage-server cache-miss
17 http fetch GET 200 https://registry.npmjs.org/@angular%2flanguage-server 6ms (cache hit)
18 silly packumentCache full:https://registry.npmjs.org/@angular%2flanguage-server set size:346643 disposed:false
19 silly placeDep ROOT @angular/language-server@ OK for:  want: 5.6.3
20 verbose type version
21 verbose stack @angular/language-server: No matching version found for @angular/language-server@5.6.3.
21 verbose stack     at module.exports (/Users/nevadascout/.nvm/versions/node/v20.16.0/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
21 verbose stack     at RegistryFetcher.manifest (/Users/nevadascout/.nvm/versions/node/v20.16.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:130:54)
21 verbose stack     at async #fetchManifest (/Users/nevadascout/.nvm/versions/node/v20.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1199:20)
21 verbose stack     at async #nodeFromEdge (/Users/nevadascout/.nvm/versions/node/v20.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1037:19)
21 verbose stack     at async #buildDepStep (/Users/nevadascout/.nvm/versions/node/v20.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:901:11)
21 verbose stack     at async Arborist.buildIdealTree (/Users/nevadascout/.nvm/versions/node/v20.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
21 verbose stack     at async Promise.all (index 1)
21 verbose stack     at async Arborist.reify (/Users/nevadascout/.nvm/versions/node/v20.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
21 verbose stack     at async Install.exec (/Users/nevadascout/.nvm/versions/node/v20.16.0/lib/node_modules/npm/lib/commands/install.js:150:5)
21 verbose stack     at async Npm.exec (/Users/nevadascout/.nvm/versions/node/v20.16.0/lib/node_modules/npm/lib/npm.js:207:9)
22 error code ETARGET
23 error notarget No matching version found for @angular/language-server@5.6.3.
24 error notarget In most cases you or one of your dependencies are requesting
24 error notarget a package version that doesn't exist.
25 silly unfinished npm timer reify 1729584485305
26 silly unfinished npm timer reify:loadTrees 1729584485306
27 verbose cwd /Users/nevadascout/Library/Application Support/Zed/extensions/work/angular
28 verbose os Darwin 24.0.0
29 verbose node v20.16.0
30 verbose npm  v10.8.1
31 verbose exit 1
32 verbose code 1
```

And here are the full logs from starting Zed showing the errors in context:
```
2024-10-22T10:07:17.126203+02:00 [INFO] ========== starting zed ==========
2024-10-22T10:07:17.12684+02:00 [INFO] Opening main db
2024-10-22T10:07:17.127918+02:00 [INFO] Opening main db
2024-10-22T10:07:17.147234+02:00 [INFO] Using git binary path: Some("/Applications/Zed.app/Contents/MacOS/git")
2024-10-22T10:07:17.278758+02:00 [INFO] initializing context server client
2024-10-22T10:07:17.27888+02:00 [INFO] Registering built-in prompt template: content_prompt
2024-10-22T10:07:17.279206+02:00 [INFO] Registering built-in prompt template: edit_workflow
2024-10-22T10:07:17.279445+02:00 [INFO] Registering built-in prompt template: project_slash_command
2024-10-22T10:07:17.279595+02:00 [INFO] Registering built-in prompt template: step_resolution
2024-10-22T10:07:17.279964+02:00 [INFO] Registering built-in prompt template: terminal_assistant_prompt
2024-10-22T10:07:17.280326+02:00 [INFO] No prompt template overrides directory found at /Users/nevadascout/.config/zed/prompt_overrides. Using built-in prompts.
2024-10-22T10:07:17.28066+02:00 [INFO] extensions updated. loading 3, reloading 0, unloading 0
2024-10-22T10:07:17.318816+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.319058+02:00 [INFO] Opening main db
2024-10-22T10:07:17.319191+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.31934+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.319822+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.320177+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.320403+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.320543+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.320746+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.320922+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.32209+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.324265+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.337616+02:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-10-22T10:07:17.35048+02:00 [INFO] Opening main db
2024-10-22T10:07:17.351002+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.353793+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.353932+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.354517+02:00 [INFO] Opening main db
2024-10-22T10:07:17.378867+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.379259+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.39014+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.44545+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.496526+02:00 [INFO] attempting to start language server "vtsls", path: "/Users/nevadascout/dev/snip/now/ui", id: 1
2024-10-22T10:07:17.496723+02:00 [INFO] attempting to start language server "eslint", path: "/Users/nevadascout/dev/snip/now/ui", id: 2
2024-10-22T10:07:17.496945+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-22T10:07:17.497196+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-22T10:07:17.500499+02:00 [INFO] fetching latest version of language server "eslint"
2024-10-22T10:07:17.500739+02:00 [INFO] downloading language server "eslint"
2024-10-22T10:07:17.50134+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.503022+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-22T10:07:17.503399+02:00 [INFO] Node runtime install_if_needed
2024-10-22T10:07:17.504758+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:17.582684+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-22T10:07:17.584529+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:07:18.092216+02:00 [INFO] set environment variables from shell:/bin/zsh, path:/Users/nevadascout/.bun/bin:/Users/nevadascout/.nvm/versions/node/v20.16.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/nevadascout/.jenv/shims:/opt/homebrew/Cellar/jenv/0.5.6/bin:/Users/nevadascout:/Users/nevadascout/Library/Python/3.7/bin:/Users/nevadascout/.local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/nevadascout/.cargo/bin
2024-10-22T10:07:18.37391+02:00 [INFO] fetching latest version of language server "vtsls"
2024-10-22T10:07:18.465533+02:00 [INFO] using project environment for language server LanguageServerName("eslint")
2024-10-22T10:07:18.474411+02:00 [INFO] starting language server process. binary path: "/Users/nevadascout/Library/Application Support/Zed/node/node-v22.5.1-darwin-arm64/bin/node", working directory: "/Users/nevadascout/dev/snip/now/ui", args: ["--max-old-space-size=8192", "/Users/nevadascout/Library/Application Support/Zed/languages/eslint/vscode-eslint-2.4.4/vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-10-22T10:07:18.590382+02:00 [WARN] unhandled capability registration: Registration { id: "463b6675-bec7-4408-86a1-2aba3c244200", method: "workspace/didChangeConfiguration", register_options: Some(Object {}) }
2024-10-22T10:07:18.598848+02:00 [WARN] unhandled capability registration: Registration { id: "1f5a2866-9620-4fbf-b522-bbf857045552", method: "workspace/didChangeWorkspaceFolders", register_options: Some(Object {}) }
2024-10-22T10:07:19.665886+02:00 [INFO] downloading language server "vtsls"

2024-10-22T10:07:19.869575+02:00 [INFO] using project environment for language server LanguageServerName("vtsls")
2024-10-22T10:07:19.869707+02:00 [INFO] starting language server process. binary path: "/Users/nevadascout/.nvm/versions/node/v20.16.0/bin/node", working directory: "/Users/nevadascout/dev/snip/now/ui", args: ["/Users/nevadascout/Library/Application Support/Zed/languages/vtsls/node_modules/@vtsls/language-server/bin/vtsls.js", "--stdio"]


2024-10-22T10:07:21.666096+02:00 [INFO] Language server with id 2 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/nevadascout/dev/snip/now/ui/now-src/apps/frontend/src/app/models/device-base/device-base.model.ts",
  "state": 1,
  "validationTime": 2833
}
2024-10-22T10:07:31.616481+02:00 [INFO] compiling Rust extension /Users/nevadascout/dev/zed-angular
2024-10-22T10:07:33.779572+02:00 [INFO] downloading wasi adapter module to /Users/nevadascout/Library/Application Support/Zed/extensions/build/wasi_snapshot_preview1.reactor.wasm
2024-10-22T10:07:34.735022+02:00 [INFO] compiling Rust crate for extension /Users/nevadascout/dev/zed-angular
2024-10-22T10:07:52.401586+02:00 [INFO] compiled Rust crate for extension /Users/nevadascout/dev/zed-angular
2024-10-22T10:07:52.409339+02:00 [INFO] encoding wasm component for extension /Users/nevadascout/dev/zed-angular
2024-10-22T10:07:52.414841+02:00 [INFO] extension /Users/nevadascout/dev/zed-angular written to /Users/nevadascout/dev/zed-angular/extension.wasm
2024-10-22T10:07:52.415091+02:00 [INFO] compiled Rust extension /Users/nevadascout/dev/zed-angular
2024-10-22T10:07:52.415196+02:00 [INFO] compiling grammar angular for extension /Users/nevadascout/dev/zed-angular
2024-10-22T10:07:52.415346+02:00 [INFO] downloading wasi-sdk to /Users/nevadascout/Library/Application Support/Zed/extensions/build/wasi-sdk
2024-10-22T10:07:56.127641+02:00 [INFO] checking out angular parser
2024-10-22T10:07:57.148874+02:00 [INFO] compiling angular parser
2024-10-22T10:08:01.034667+02:00 [INFO] compiled grammar angular for extension /Users/nevadascout/dev/zed-angular
2024-10-22T10:08:01.034815+02:00 [INFO] finished compiling extension /Users/nevadascout/dev/zed-angular
2024-10-22T10:08:01.365374+02:00 [INFO] rebuilt extension index in 10.505458ms
2024-10-22T10:08:01.365774+02:00 [INFO] extensions updated. loading 1, reloading 0, unloading 0
2024-10-22T10:08:01.367641+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-22T10:08:01.540293+02:00 [INFO] Language server with id 2 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/nevadascout/dev/snip/now/ui/now-src/apps/frontend/src/app/models/device-base/device-base.model.ts",
  "state": 1,
  "validationTime": 93
}
2024-10-22T10:08:01.594417+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-22T10:08:01.594563+02:00 [INFO] attempting to start language server "ts", path: "/Users/nevadascout/dev/snip/now/ui", id: 3
2024-10-22T10:08:01.594721+02:00 [INFO] attempting to start language server "vscode-angular-language-server", path: "/Users/nevadascout/dev/snip/now/ui", id: 4
2024-10-22T10:08:01.595428+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:08:01.70422+02:00 [INFO] Language server with id 2 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/nevadascout/dev/snip/now/ui/now-src/apps/frontend/src/app/models/device-base/device-base.model.ts",
  "state": 1,
  "validationTime": 63
}
2024-10-22T10:08:04.085774+02:00 [ERROR] Failed to start language server "ts": failed to execute npm install subcommand:
stdout: ""
stderr: "npm error code ETARGET\nnpm error notarget No matching version found for @angular/language-server@5.6.3.\nnpm error notarget In most cases you or one of your dependencies are requesting\nnpm error notarget a package version that doesn't exist.\nnpm error A complete log of this run can be found in: /Users/nevadascout/Library/Application Support/Zed/node/cache/_logs/2024-10-22T08_08_03_929Z-debug-0.log\n"
2024-10-22T10:08:04.08592+02:00 [ERROR] server stderr: ""
2024-10-22T10:08:05.327147+02:00 [ERROR] Failed to start language server "vscode-angular-language-server": failed to execute npm install subcommand:
stdout: ""
stderr: "npm error code ETARGET\nnpm error notarget No matching version found for @angular/language-server@5.6.3.\nnpm error notarget In most cases you or one of your dependencies are requesting\nnpm error notarget a package version that doesn't exist.\nnpm error A complete log of this run can be found in: /Users/nevadascout/Library/Application Support/Zed/node/cache/_logs/2024-10-22T08_08_05_192Z-debug-0.log\n"
2024-10-22T10:08:05.327283+02:00 [ERROR] server stderr: ""
2024-10-22T10:08:23.896563+02:00 [INFO] attempting to start language server "tailwindcss-language-server", path: "/Users/nevadascout/dev/snip/now/ui", id: 5
2024-10-22T10:08:23.896716+02:00 [INFO] attempting to start language server "vscode-html-language-server", path: "/Users/nevadascout/dev/snip/now/ui", id: 6
2024-10-22T10:08:23.896842+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-22T10:08:23.897032+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-22T10:08:23.897705+02:00 [INFO] fetching latest version of language server "tailwindcss-language-server"
2024-10-22T10:08:23.897942+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-22T10:08:24.02047+02:00 [INFO] Language server with id 2 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/nevadascout/dev/snip/now/ui/now-src/apps/frontend/src/app/models/device-base/device-base.model.ts",
  "state": 1,
  "validationTime": 73
}
2024-10-22T10:08:24.513344+02:00 [INFO] downloading language server "tailwindcss-language-server"
2024-10-22T10:08:25.195258+02:00 [INFO] using project environment for language server LanguageServerName("tailwindcss-language-server")
2024-10-22T10:08:25.195413+02:00 [INFO] starting language server process. binary path: "/Users/nevadascout/.nvm/versions/node/v20.16.0/bin/node", working directory: "/Users/nevadascout/dev/snip/now/ui", args: ["/Users/nevadascout/Library/Application Support/Zed/languages/tailwindcss-language-server/node_modules/.bin/tailwindcss-language-server", "--stdio"]
2024-10-22T10:08:25.687123+02:00 [WARN] unhandled capability registration: Registration { id: "52a2681b-0924-47a1-86ee-6ed0952ebee0", method: "workspace/didChangeWorkspaceFolders", register_options: Some(Object {}) }
2024-10-22T10:08:28.489674+02:00 [INFO] starting language server process. binary path: "/Users/nevadascout/.nvm/versions/node/v20.16.0/bin/node", working directory: "/Users/nevadascout/dev/snip/now/ui", args: ["/Users/nevadascout/Library/Application Support/Zed/extensions/work/html/node_modules/@zed-industries/vscode-langservers-extracted/bin/vscode-html-language-server", "--stdio"]
2024-10-22T10:08:28.705365+02:00 [WARN] unhandled capability registration: Registration { id: "6291a6b6-6a37-4804-ac3d-2cc68a6ff246", method: "workspace/didChangeWorkspaceFolders", register_options: Some(Object {}) }

```

**Comment by nevadascout** [comment]
I see in the extension code there is a function `typescript_exists_for_worktree` which tries to read the package.json file. As I have two package.json files in different folders, I suspect that this does not work properly for my repo - or indeed any other repo that has more than one package.json file inside it.

I suspect that this is a separate issue to the one I am seeing though.

```
let package_json = worktree.read_text_file("package.json")?;
```

<img width="628" alt="Screenshot 2024-10-22 at 10 32 31" src="https://github.com/user-attachments/assets/fe9d772a-6266-4382-a74f-c68c2e770e96">

---

I would also point out that the Angular plugin for VS Code that uses `vscode-angular-language-server` works fine when I open the same monorepo in VS Code at the root level.

**Comment by nathansbradshaw** [comment]
This is an exciting moment! Not that it failed for you, but that it's being beta tested by others! Thank you for your report, I'll look into it as soon as I get a chance. 

The fact that it installed a very old version of angular lsp is a little concerning, at one point I had it base the angular version off the angular core version, but I should have switched that code back. I'll look into the logic again and make sure everything works correctly.


My logic flow is almost verbatim from the Vue extension, so it's possible that one fails for you as well?

**Comment by nathansbradshaw** [comment]
I've got a bug on line 54, it's installing angular at the ta version *facepalm*

**Comment by nathansbradshaw** [comment]
It should be 
```
            let result = zed::npm_install_package(PACKAGE_NAME, &version);
```

I won't be able to fix it for a few hours, but you're welcome to open a pr or wait

**Comment by nevadascout** [comment]
> This is an exciting moment! Not that it failed for you, but that it's being beta tested by others! 

Indeed! I'm happy to help you debug this. I've applied the fix that you suggested locally and it works! I'll open a PR 👍

**Comment by nevadascout** [comment]
I'm seeing some other issues now that the extension is running - I'll make new tickets for those. Maybe I can take a look at fixing those myself 🤔
